/**
 * Copyright(c) Starleaf Ltd. 2016.
 */


"use strict";


//Small library for plan b interop - Designed to be run on chrome.
//Assumes you will do the following - convert unified plan received on the wire into plan B
//before setting the remote description
//Convert plan b generated by chrome into unified plan prior to sending.




var Interop = function () {
    var cache = {};

    var toUnifiedPlan = function(desc) {
        var uplan = require('./on_chrome/to-unified-plan')(desc, cache);
        //cache a copy
        cache.local = uplan.sdp;
        return uplan;
    };

    var toPlanB = function(desc) {
        //cache the last unified plan we received on the wire
        cache.remote = desc.sdp;
        return require('./on_chrome/to-plan-b')(desc);
    };


    var that = {};
    that.toUnifiedPlan = toUnifiedPlan;
    that.toPlanB = toPlanB;
    return that;
};

module.exports = Interop;